groups:
  - name: all
    jobs:
      - pull-request-integration-test

shared:
  - &run
    task: terraformci
    file: terraform-provider-alicloud/ci/tasks/pull-request.yml
    params:
      ALICLOUD_ACCESS_KEY: {{alicloud_access_key}}
      ALICLOUD_SECRET_KEY: {{alicloud_secret_key}}
      ALICLOUD_ACCOUNT_ID: {{alicloud_accound_id}}
      FC_SERVICE: {{alicloud_fc_service_name}}
      FC_REGION: {{alicloud_fc_region}}
      OSS_BUCKET_NAME: {{alicloud_oss_bucket_name}}
      OSS_BUCKET_REGION: {{alicloud_oss_bucket_region}}
      GITHUB_TOKEN: {{github_token}}

jobs:
- name: pull-request-integration-test
  plan:
  - in_parallel:
    - get: terraform-provider-alicloud
      resource: github-pr-comment-ping
      trigger: true
      version: every
      params:
        source_path: .
    - get: aliyun-cli
      resource: aliyun-cli
    - get: trigger
      trigger: true
      resource: duration
  - <<: *run

resources:

- name: aliyun-cli
  type: s3
  source:
    access_key_id: {{aliyun_cli_access_key}}
    secret_access_key: {{aliyun_cli_secret_key}}
    bucket: {{aliyun_cli_bucket}}
    regexp: .*-cli-linux-3\.0\.(\d+)-amd64\.tgz
    region_name: {{aliyun_cli_region}}
    endpoint: oss-((aliyun_cli_region)).aliyuncs.com

- name: duration
  type: time
  source:
    start: 09:00 AM
    stop: 10:00 PM
    days: [Monday, Tuesday, Wednesday, Thursday, Friday]
    location: {{time_location}}

- name: github-pr-comment-ping
  type: github-pr-comment-resource
  source:
    repository: aliyun/terraform-provider-alicloud
    access_token: {{github_token}}
    review_states: ["approved", "commented"]
    when: latest
    comments: ["^approved$"]


resource_types:
  - name: github-pr-comment-resource
    type: docker-image
    source:
      repository: ndrjng/concourse-github-pr-comment-resource
